name: Package Node for Windows

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  package-windows-x64:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm i -g nexe
      - run: nexe -t windows-x64-12.16.3 index.js
      - name: Archive .exe
        uses: actions/upload-artifact@v2
        with:
          name: test-prod
          path: |
            endomondo-exporter.exe
            README.md
