name: Package Node for Windows

on: push

jobs:
  package-windows-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npx nexe -t windows-x64-12.16.3 index.js
      - name: Archive .exe
        uses: actions/upload-artifact@v2
        with:
          name: test-prod
          path: |
            endomondo-exporter.exe
            README.md
            settings.json
