name: Package Node for Windows

on: push

jobs:
  package-windows-64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npx nexe -t windows-x64-12.16.3 index.js
      - name: Archive .exe
        uses: actions/upload-artifact@v2
        with:
          name: endomondo-exporter-win-64
          path: |
            endomondo-exporter.exe
            README.md
            settings.json
  package-windows-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npx nexe -t windows-x86-12.16.3 index.js
      - name: Archive .exe
        uses: actions/upload-artifact@v2
        with:
          name: endomondo-exporter-win-x86
          path: |
            endomondo-exporter.exe
            README.md
            settings.json
  package-linux-64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npx nexe -t linux-x64-12.16.2 index.js
      - name: Archive .exe
        uses: actions/upload-artifact@v2
        with:
          name: endomondo-exporter-linux-64
          path: |
            endomondo-exporter
            README.md
            settings.json
